[tool.poetry]
name = "runtime-analytics"
version = "0.1.0"
description = "A lightweight log analysis tool with prompt-based querying and GUI"
authors = ["Your Name <you@example.com>"]
packages = [
    { include = "runtime_analytics" }
]

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.0"
streamlit = "^1.33.0"
pyarrow = "^15.0.0"
sqlalchemy = "^2.0.30"
pydantic = "^2.11.5"
pydantic-settings = "^2.9.1"
scikit-learn = "^1.4.2"
numpy = "^1.26.4"
sqlite-utils = "^3.36.0"
pyyaml = "^6.0"
sentence-transformers = "^4.1.0"
