prompts:
  sns duration by riskdate:
    function: sns_duration_by_riskdate
    description: Show the total and average duration of SNSI jobs grouped by riskdate.
    tags: [duration, sns, time-series]

  job count by type:
    function: job_count_by_type
    description: Count how many jobs were run for each job type.
    tags: [summary, types]

  stdv > 300:
    function: stdv_long_jobs
    description: List all STDV jobs with duration greater than 300 seconds.
    tags: [filter, stdv, duration]
